version: '3.8'

services:
  mainframe:
    build: ./mainframe
    container_name: mainframe-tk4
    ports:
      - "3270:3270"
      - "8038:8038"
    volumes:
      - ./mainframe/mvs_data:/mvs
    stdin_open: true
    tty: true
